/* =====================================================================
   OBRAS — una entrada por obra. El orden acá es el orden en la web.
   TÍTULOS PROVISORIOS (descriptivos) — reemplazar por los títulos reales de la artista.
   year y size se completan cuando se tengan (year: 2019, size: "80 × 100 cm").
   Para agregar una obra: python3 tools/optimize_images.py _originals/foto.jpg -> id = nombre del archivo
   Campos opcionales: series, description, available (true por defecto), year, size
   ===================================================================== */
window.WORKS = [
  { id: "mujer-espada-mariposa", title: { es: "Mujer con espada y mariposa", en: "Woman with sword and butterfly" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "cuervo-tierra", title: { es: "Cuervo y la Tierra", en: "Crow and the Earth" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "abedules-azul", title: { es: "Abedules en azul", en: "Birches in blue" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Árboles", en: "Trees" } },
  { id: "pareja-sandia", title: { es: "Pareja en la sandía", en: "Couple on a watermelon" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "mujer-camara", title: { es: "Mujer con cámara", en: "Woman with camera" }, technique: { es: "Técnica mixta", en: "Mixed media" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "palomas-pochoclo", title: { es: "Palomas y pochoclo", en: "Pigeons and popcorn" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "retrato-cuchillo", title: { es: "Retrato con cuchillo", en: "Portrait with knife" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "arbol-rojo", title: { es: "Árbol rojo", en: "Red tree" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Árboles", en: "Trees" } },
  { id: "sonrisa", title: { es: "Sonrisa", en: "Smile" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "pajaro-azul-billetes", title: { es: "Pájaro azul sobre billetes", en: "Blue bird on banknotes" }, technique: { es: "Técnica mixta", en: "Mixed media" }, series: { es: "Animales", en: "Animals" } },
  { id: "mujer-pajaro", title: { es: "Mujer con pájaro", en: "Woman with bird" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "puente", title: { es: "Puente", en: "Bridge" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Árboles", en: "Trees" } },
  { id: "hombre-copa", title: { es: "Hombre con copa", en: "Man with a glass" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "jaula", title: { es: "Jaula", en: "Cage" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "mujer-sonriendo", title: { es: "Mujer sonriendo", en: "Smiling woman" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "cuervo-corazon", title: { es: "Cuervo con corazón", en: "Crow with heart" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "nino-alambrado", title: { es: "Niño en el alambrado", en: "Boy at the fence" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "abedules-amarillo", title: { es: "Abedules en amarillo", en: "Birches in yellow" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Árboles", en: "Trees" } },
  { id: "rostro-burbujas", title: { es: "Rostro entre burbujas", en: "Face among bubbles" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "pajaro-dolar", title: { es: "Pájaro sobre un dólar", en: "Bird on a dollar" }, technique: { es: "Técnica mixta", en: "Mixed media" }, series: { es: "Animales", en: "Animals" } },
  { id: "mujer-uvas", title: { es: "Mujer con uvas", en: "Woman with grapes" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "ojo-pez", title: { es: "Ojo de pez", en: "Fish eye" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "retrato-lineas-naranjas", title: { es: "Retrato en líneas naranjas", en: "Portrait in orange lines" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "arboles-rojos", title: { es: "Árboles rojos", en: "Red trees" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Árboles", en: "Trees" } },
  { id: "mujer-brazos-cruzados", title: { es: "Mujer de brazos cruzados", en: "Woman with crossed arms" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "pajaro-rojo-soga", title: { es: "Pájaro rojo en la soga", en: "Red bird on the rope" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "mujer-baldes", title: { es: "Mujer con baldes", en: "Woman with buckets" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "dibujo-manos", title: { es: "Manos", en: "Hands" }, technique: { es: "Dibujo sobre papel", en: "Drawing on paper" }, series: { es: "Dibujos", en: "Drawings" } },
  { id: "nino-gateando", title: { es: "Niño gateando", en: "Crawling child" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "cuervo", title: { es: "Cuervo", en: "Crow" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "mujer-jardin", title: { es: "Mujer en el jardín", en: "Woman in the garden" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "abedules-rojo", title: { es: "Abedules en rojo", en: "Birches in red" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Árboles", en: "Trees" } },
  { id: "camion", title: { es: "El camión", en: "The truck" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "pajaros-ojo", title: { es: "Pájaros y ojo", en: "Birds and eye" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "futbolista", title: { es: "Futbolista", en: "Footballer" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "relieve-azul", title: { es: "Azul", en: "Blue" }, technique: { es: "Técnica mixta", en: "Mixed media" }, series: { es: "Técnica mixta", en: "Mixed media" } },
  { id: "hombre-muro", title: { es: "Hombre sentado en el muro", en: "Man sitting on the wall" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "pajaro-diario", title: { es: "Pájaro sobre diario", en: "Bird on newspaper" }, technique: { es: "Técnica mixta", en: "Mixed media" }, series: { es: "Animales", en: "Animals" } },
  { id: "canon", title: { es: "Cañón", en: "Canyon" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "abedules-turquesa", title: { es: "Abedules turquesa", en: "Turquoise birches" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Árboles", en: "Trees" } },
  { id: "mujer-arbol-ciudad", title: { es: "Mujer árbol en la ciudad", en: "Tree woman in the city" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "pajaro-corazon", title: { es: "Pájaro y corazón", en: "Bird and heart" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "nino-botella", title: { es: "Niño con botella", en: "Boy with bottle" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "dibujo-pareja", title: { es: "Pareja", en: "Couple" }, technique: { es: "Dibujo sobre papel", en: "Drawing on paper" }, series: { es: "Dibujos", en: "Drawings" } },
  { id: "hombre-sombrero-paja", title: { es: "Hombre con sombrero de paja", en: "Man with straw hat" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "pajaros-rojo", title: { es: "Pájaros sobre rojo", en: "Birds on red" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "frente-ciudad", title: { es: "Frente a la ciudad", en: "Facing the city" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "abedules-dorado", title: { es: "Abedules sobre dorado", en: "Birches on gold" }, technique: { es: "Técnica mixta", en: "Mixed media" }, series: { es: "Árboles", en: "Trees" } },
  { id: "hamaca", title: { es: "Hamaca", en: "Swing" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "pez-colores", title: { es: "Pez de colores", en: "Colourful fish" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "nina-rosa", title: { es: "Niña con rosa", en: "Girl with rose" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "pajaro-pasto", title: { es: "Pájaro en el pasto", en: "Bird in the grass" }, technique: { es: "Técnica mixta", en: "Mixed media" }, series: { es: "Animales", en: "Animals" } },
  { id: "hombre-montana", title: { es: "Hombre recostado en la montaña", en: "Man lying on the mountain" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "abedules-otono", title: { es: "Abedules en otoño", en: "Birches in autumn" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Árboles", en: "Trees" } },
  { id: "hombre-vina", title: { es: "Hombre en la viña", en: "Man in the vineyard" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "pajaro-avion-papel", title: { es: "Pájaro y avión de papel", en: "Bird and paper plane" }, technique: { es: "Técnica mixta", en: "Mixed media" }, series: { es: "Animales", en: "Animals" } },
  { id: "nina-arbol-rojo", title: { es: "Niña bajo el árbol rojo", en: "Girl under the red tree" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "dibujo-colibri", title: { es: "Colibrí", en: "Hummingbird" }, technique: { es: "Dibujo sobre papel", en: "Drawing on paper" }, series: { es: "Dibujos", en: "Drawings" } },
  { id: "figura-niebla", title: { es: "Figura en la niebla", en: "Figure in the fog" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "pajaro-rojo-diario", title: { es: "Pájaro rojo sobre diario", en: "Red bird on newspaper" }, technique: { es: "Técnica mixta", en: "Mixed media" }, series: { es: "Animales", en: "Animals" } },
  { id: "la-mesa", title: { es: "La mesa", en: "The table" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "troncos", title: { es: "Troncos", en: "Trunks" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Árboles", en: "Trees" } },
  { id: "pajaro-alambre", title: { es: "Pájaro tras el alambre", en: "Bird behind the wire" }, technique: { es: "Técnica mixta", en: "Mixed media" }, series: { es: "Animales", en: "Animals" } },
  { id: "mujer-verde", title: { es: "Mujer en verde", en: "Woman in green" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "pichones-aviones", title: { es: "Pichones y aviones de papel", en: "Chicks and paper planes" }, technique: { es: "Técnica mixta", en: "Mixed media" }, series: { es: "Animales", en: "Animals" } },
  { id: "rostro-edificios", title: { es: "Rostro con edificios", en: "Face with buildings" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "arbol-verde", title: { es: "Árbol verde", en: "Green tree" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Árboles", en: "Trees" } },
  { id: "rostros-cruz-roja", title: { es: "Rostros con cruz roja", en: "Faces with red cross" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "dos-cuervos", title: { es: "Dos cuervos", en: "Two crows" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "mujer-maizal", title: { es: "Mujer en el maizal", en: "Woman in the cornfield" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Retratos", en: "Portraits" } },
  { id: "pajaros-uvas", title: { es: "Pájaros amarillos y uvas", en: "Yellow birds and grapes" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "dibujo-desnudo", title: { es: "Desnudo", en: "Nude" }, technique: { es: "Dibujo sobre papel", en: "Drawing on paper" }, series: { es: "Dibujos", en: "Drawings" } },
  { id: "arbol-sol", title: { es: "Árbol al sol", en: "Tree in the sun" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Árboles", en: "Trees" } },
  { id: "arbol-pajaros", title: { es: "Árbol con pájaros", en: "Tree with birds" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "dibujo-figura-sentada", title: { es: "Figura sentada", en: "Seated figure" }, technique: { es: "Dibujo sobre papel", en: "Drawing on paper" }, series: { es: "Dibujos", en: "Drawings" } },
  { id: "pajaro-mapa", title: { es: "Pájaro con mapa", en: "Bird with map" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "bosque-rojo", title: { es: "Bosque rojo", en: "Red forest" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Árboles", en: "Trees" } },
  { id: "pez", title: { es: "Pez", en: "Fish" }, technique: { es: "Técnica mixta", en: "Mixed media" }, series: { es: "Animales", en: "Animals" } },
  { id: "dibujo-manos-2", title: { es: "Manos II", en: "Hands II" }, technique: { es: "Dibujo sobre papel", en: "Drawing on paper" }, series: { es: "Dibujos", en: "Drawings" } },
  { id: "rana", title: { es: "Rana", en: "Frog" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "arbol-lamparas", title: { es: "Árbol con lámparas", en: "Tree with lamps" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Árboles", en: "Trees" } },
  { id: "vaca-rejas", title: { es: "Vaca tras las rejas", en: "Cow behind bars" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "dibujo-figura", title: { es: "Figura", en: "Figure" }, technique: { es: "Dibujo sobre papel", en: "Drawing on paper" }, series: { es: "Dibujos", en: "Drawings" } },
  { id: "naturaleza-muerta-pajaro", title: { es: "Naturaleza muerta con pájaro", en: "Still life with bird" }, technique: { es: "Óleo sobre tela", en: "Oil on canvas" }, series: { es: "Animales", en: "Animals" } },
  { id: "dibujo-dos-pajaros", title: { es: "Dos pájaros", en: "Two birds" }, technique: { es: "Dibujo sobre papel", en: "Drawing on paper" }, series: { es: "Dibujos", en: "Drawings" } },
  { id: "pajaro-red", title: { es: "Pájaro en la red", en: "Bird in the net" }, technique: { es: "Técnica mixta", en: "Mixed media" }, series: { es: "Animales", en: "Animals" } },
  { id: "grabado-pajaro", title: { es: "Pájaro", en: "Bird" }, technique: { es: "Grabado sobre fondo dorado", en: "Print on gold ground" }, series: { es: "Dibujos", en: "Drawings" } },
  { id: "telefonos-1", title: { es: "Teléfonos I", en: "Telephones I" }, technique: { es: "Fotografía", en: "Photograph" }, series: { es: "Fotografía", en: "Photography" } },
  { id: "telefonos-2", title: { es: "Teléfonos II", en: "Telephones II" }, technique: { es: "Fotografía", en: "Photograph" }, series: { es: "Fotografía", en: "Photography" } },
];
